language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
addons:
  chrome: stable
matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
install:
  pip install tox-travis
before_script:
  - ./scripts/setup_chromedriver.sh
  - ./scripts/setup_geckodriver.sh
script:
  - tox -- --driver Chrome
  - tox -- --driver Firefox
branches:
  only:
  - master
