language: python
dist: xenial
python:
  - 2.7
  - 3.6
  - 3.5
  - 3.7
install:
  pip install tox-travis
before_script:
  - wget -N https://chromedriver.storage.googleapis.com/76.0.3809.12/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -P ~/
  - tar xvzf ~/geckodriver-v0.24.0-linux64.tar.gz -C ~/
  - rm ~/geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv -f ~/geckodriver /usr/local/share/
  - sudo chmod +x /usr/local/share/geckodriver
script:
  - tox
